# Generated by Django 6.0 on 2025-12-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('pattern', models.CharField(max_length=255)),
                ('total', models.IntegerField(default=0)),
                ('currency', models.CharField(default='MRU', max_length=10)),
            ],
        ),
    ]
